export enum Status {
  MENUNGGU_KONFIRMASI = 'MENUNGGU_KONFIRMASI',
  DIPROSES = 'DIPROSES',
  DIKIRIM = 'DIKIRIM',
  SELESAI = 'SELESAI',
}

export enum StatusPesanan {
  MENUNGGU_KONFIRMASI = 'MENUNGGU_KONFIRMASI',
  DIPROSES = 'DIPROSES',
  PENDING = 'PENDING',
  DIKIRIM = 'DIKIRIM',
  SELESAI = 'SELESAI',
  DITOLAK = 'DITOLAK',
}

